use strict;

use vars qw(%inc_translations);
BEGIN { %inc_translations = (
		"SimulationBase/GTruth.h" => "nusimdata/SimulationBase/GTruth.",
		"SimulationBase/MCFlux.h" => "nusimdata/SimulationBase/MCFlux.",
		"SimulationBase/MCNeutrino.h" => "nusimdata/SimulationBase/MCNeutrino.",
		"SimulationBase/MCParticle.h" => "nusimdata/SimulationBase/MCParticle.",
		"SimulationBase/MCTrajectory.h" => "nusimdata/SimulationBase/MCTrajectory.",
		"SimulationBase/MCTruth.h" => "nusimdata/SimulationBase/MCTruth.",
		"SimulationBase/classes.h" => "nusimdata/SimulationBase/classes.",
		"EventDisplayBase/ButtonBar.h" => "nutools/EventDisplayBase/ButtonBar.",
		"EventDisplayBase/Canvas.h" => "nutools/EventDisplayBase/Canvas.",
		"EventDisplayBase/ColorScale.h" => "nutools/EventDisplayBase/ColorScale.",
		"EventDisplayBase/Colors.h" => "nutools/EventDisplayBase/Colors.",
		"EventDisplayBase/DisplayWindow.h" => "nutools/EventDisplayBase/DisplayWindow.",
		"EventDisplayBase/EditMenu.h" => "nutools/EventDisplayBase/EditMenu.",
		"EventDisplayBase/EventDisplay.h" => "nutools/EventDisplayBase/EventDisplay.",
		"EventDisplayBase/EventHolder.h" => "nutools/EventDisplayBase/EventHolder.",
		"EventDisplayBase/FileMenu.h" => "nutools/EventDisplayBase/FileMenu.",
		"EventDisplayBase/Functors.h" => "nutools/EventDisplayBase/Functors.",
		"EventDisplayBase/HelpMenu.h" => "nutools/EventDisplayBase/HelpMenu.",
		"EventDisplayBase/JobMenu.h" => "nutools/EventDisplayBase/JobMenu.",
		"EventDisplayBase/LinkDef.h" => "nutools/EventDisplayBase/LinkDef.",
		"EventDisplayBase/ListWindow.h" => "nutools/EventDisplayBase/ListWindow.",
		"EventDisplayBase/MenuBar.h" => "nutools/EventDisplayBase/MenuBar.",
		"EventDisplayBase/NavState.h" => "nutools/EventDisplayBase/NavState.",
		"EventDisplayBase/ObjListCanvas.h" => "nutools/EventDisplayBase/ObjListCanvas.",
		"EventDisplayBase/ParameterSetEdit.h" => "nutools/EventDisplayBase/ParameterSetEdit.",
		"EventDisplayBase/ParameterSetEditDialog.h" => "nutools/EventDisplayBase/ParameterSetEditDialog.",
		"EventDisplayBase/PrintDialog.h" => "nutools/EventDisplayBase/PrintDialog.",
		"EventDisplayBase/Printable.h" => "nutools/EventDisplayBase/Printable.",
		"EventDisplayBase/RootEnv.h" => "nutools/EventDisplayBase/RootEnv.",
		"EventDisplayBase/ScanOptions.h" => "nutools/EventDisplayBase/ScanOptions.",
		"EventDisplayBase/ScanWindow.h" => "nutools/EventDisplayBase/ScanWindow.",
		"EventDisplayBase/ServiceTable.h" => "nutools/EventDisplayBase/ServiceTable.",
		"EventDisplayBase/StatusBar.h" => "nutools/EventDisplayBase/StatusBar.",
		"EventDisplayBase/View2D.h" => "nutools/EventDisplayBase/View2D.",
		"EventDisplayBase/View3D.h" => "nutools/EventDisplayBase/View3D.",
		"EventDisplayBase/WindowMenu.h" => "nutools/EventDisplayBase/WindowMenu.",
		"EventDisplayBase/evdb.h" => "nutools/EventDisplayBase/evdb.",
		"EventGeneratorBase/CRY/CRYHelper.h" => "nutools/EventGeneratorBase/CRY/CRYHelper.",
		"EventGeneratorBase/GENIE/GENIEHelper.h" => "nutools/EventGeneratorBase/GENIE/GENIEHelper.",
		"EventGeneratorBase/evgenbase.h" => "nutools/EventGeneratorBase/evgenbase.",
		"G4Base/ConvertMCTruthToG4.h" => "nutools/G4Base/ConvertMCTruthToG4.",
		"G4Base/DetectorConstruction.h" => "nutools/G4Base/DetectorConstruction.",
		"G4Base/ExampleAction.h" => "nutools/G4Base/ExampleAction.",
		"G4Base/G4Helper.h" => "nutools/G4Base/G4Helper.",
		"G4Base/G4PhysListFactory.hh" => "nutools/G4Base/G4PhysListFactory.h",
		"G4Base/G4PhysListFactorySingleton.hh" => "nutools/G4Base/G4PhysListFactorySingleton.h",
		"G4Base/G4PhysicsProcessFactorySingleton.hh" => "nutools/G4Base/G4PhysicsProcessFactorySingleton.h",
		"G4Base/PrimaryParticleInformation.h" => "nutools/G4Base/PrimaryParticleInformation.",
		"G4Base/UserAction.h" => "nutools/G4Base/UserAction.",
		"G4Base/UserActionFactory.h" => "nutools/G4Base/UserActionFactory.",
		"G4Base/UserActionManager.h" => "nutools/G4Base/UserActionManager.",
		"G4NuPhysicsLists/include/G4NuPhysicsLists/G4PhysListFactory.hh" => "nutools/G4NuPhysicsLists/include/G4NuPhysicsLists/G4PhysListFactory.h",
		"G4NuPhysicsLists/include/G4NuPhysicsLists/G4PhysListFactorySingleton.hh" => "nutools/G4NuPhysicsLists/include/G4NuPhysicsLists/G4PhysListFactorySingleton.h",
		"G4NuPhysicsLists/include/G4NuPhysicsLists/G4PhysicsProcessFactorySingleton.hh" => "nutools/G4NuPhysicsLists/include/G4NuPhysicsLists/G4PhysicsProcessFactorySingleton.h",
		"G4NuPhysicsLists/include/G4NuPhysicsLists/HadronPhysicsNuBeam.hh" => "nutools/G4NuPhysicsLists/include/G4NuPhysicsLists/HadronPhysicsNuBeam.h",
		"G4NuPhysicsLists/include/G4NuPhysicsLists/NuBeam.hh" => "nutools/G4NuPhysicsLists/include/G4NuPhysicsLists/NuBeam.h",
		"G4NuPhysicsLists/include/G4NuPhysicsLists/QGSPStrFragmLundProtonBuilder.hh" => "nutools/G4NuPhysicsLists/include/G4NuPhysicsLists/QGSPStrFragmLundProtonBuilder.h",
		"IFDatabase/Column.h" => "nutools/IFDatabase/Column.",
		"IFDatabase/ColumnDef.h" => "nutools/IFDatabase/ColumnDef.",
		"IFDatabase/DBIService.h" => "nutools/IFDatabase/DBIService.",
		"IFDatabase/DataType.h" => "nutools/IFDatabase/DataType.",
		"IFDatabase/Row.h" => "nutools/IFDatabase/Row.",
		"IFDatabase/Table.h" => "nutools/IFDatabase/Table.",
		"IFDatabase/Util.h" => "nutools/IFDatabase/Util.",
		"MagneticField/MagneticField.h" => "nutools/MagneticField/MagneticField.",
		"NuBeamWeights/Conventions.h" => "nutools/NuBeamWeights/Conventions.",
		"NuBeamWeights/skzpReweight.h" => "nutools/NuBeamWeights/skzpReweight.",
		"NuReweight/GENIEReweight.h" => "nutools/NuReweight/GENIEReweight.",
		"NuReweight/ReweightLabels.h" => "nutools/NuReweight/ReweightLabels.",
		"NuReweight/art/NuReweight.h" => "nutools/NuReweight/art/NuReweight.",
		"G4Base/G4PhysListRegisterOld.icc" => "nutools/G4Base/G4PhysListRegisterOld.icc",
		"G4Base/G4PhysicsProcessRegisterOld.icc" => "nutools/G4Base/G4PhysicsProcessRegisterOld.icc",
		"G4NuPhysicsLists/G4PhysListRegisterOld.icc" => "nutools/G4NuPhysicsLists/G4PhysListRegisterOld.icc",
		"G4NuPhysicsLists/G4PhysicsProcessRegisterOld.icc" => "nutools/G4NuPhysicsLists/G4PhysicsProcessRegisterOld.icc"
                            );

      }
foreach my $inc (sort keys %inc_translations) {
  s&^(\s*#include\s+["<])\Q$inc\E([">].*)$&${1}$inc_translations{$inc}${2}& and last;
}

### Local Variables:
### mode: cperl
### End:
